server:
    port: 9998

spring:
    jpa:
        show_sql: true
        properties:
            hibernate:
                dialect: org.hibernate.dialect.MySQL5Dialect
                format_sql: true
    datasource:
        hikari:
            jdbc-url: jdbc:h2:mem://localhost/~/board;MODE=MYSQL